### ISSUE TITLE
Problem with jalaali calender

### ISSUE THREAD

**Issue by mariajhn** [Natico/fullcalendar-Jalaali#2]
Hi,
Thank you for your code

I think it changes the language to Farsi
But how can it show a Jalaali calendar?!

**Comment by Natico** [comment]
Hi,
Please give me more explanation. 
If you do the same as stated below. You should see the calendar as jallali.

Import moment-jalaali.js exactly after moment.js. You can find it in "lib/moment/moment-jalaali.js".
Import lang/fa.js or dist/lang/lang-all.js after fullcalendar.js or fullcalendar.min.js.
Put isJalaali : true in config.
Put isRTL : true in config.
Put lang : "fa" in config.

**Comment by mariajhn** [comment]
I do all of them 
but nothing change

**Comment by Natico** [comment]
As long as you do not provide more details, I can not help you. Please provide an URL address for review.

**Comment by mariajhn** [comment]
Many thanks in advance,
This is a section of my code:
` <script src="bower_components/moment/moment.js"></script>
      <script src="cal/moment-jalaali.js"></script>
      <script src="assets/js/jquery-1.11.1.min.js"></script>    
    <script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
    <script src="bower_components/angular-animate/angular-animate.js"></script>
    <script src="bower_components/angular-route/angular-route.js"></script>
    <script src="bower_components/ng-jalaali-flat-datepicker/dist/ng-jalaali-flat-datepicker.min.js"></script>  
      <script src="bower_components/angular-ui-calendar/src/calendar.js"></script>
      <script src="bower_components/fullcalendar/dist/fullcalendar.js"></script>
      <script src="cal/fa.js"></script>
      <script src="bower_components/fullcalendar/dist/gcal.js"></script>
      <script src="bower_components/angular-messages/angular-messages.js"></script>
      <script src="bower_components/angular-ui-router/release/angular-ui-router.js"></script>
      <script src="bower_components/angular-material/angular-material.js"></script>
      <script src="bower_components/angular-aria/angular-aria.js"></script>
      <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.10.0/ui-bootstrap-tpls.min.js"></script>
 `

I controller I have:
`  $scope.uiConfig = {
        calendar: {            
            
            isJalaali: true,
            isRTL: true,
            lang: 'fa',
            defaultDate: '2018-02-12',
            editable: false,`
In HTML page:
`  <div ui-calendar="uiConfig.calendar" ng-model="eventSources">`
