### ISSUE TITLE
اصلاح پوشه دمو برای نمایش تقویم به صورت فارسی 

### ISSUE THREAD

**Issue by MSehati** [Natico/fullcalendar-Jalaali#3]
سلام لطفا پوشه دمو را تغییر بدهید تا اولین بار که این کتابخانه در مرورگر نمایش داده می شود تقویم به فارسی نمایش داده بشه نه انگلیسی. این جوری کار برای توسعه یا استفاده از این کتابخانه راحت تر هست

**Comment by kasaiee** [comment]
سلام. من هم این مشکل رو دارم و متوجه نمیشم بالاخره تاریخ جلالی میشه یا اینکه فقط نوشته ها فارسی میشن
